CREATE TABLE IF NOT EXISTS authentication_manager (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS user_credential (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS budget_manager (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS report_manager (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS trip_manager (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS expense_manager (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS budget (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    amount DOUBLE,
    currency VARCHAR(255),
    description VARCHAR(255),
    type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS report (
    report_id INTEGER PRIMARY KEY AUTOINCREMENT,
    content VARCHAR(255),
    creation_date DATE
);

CREATE TABLE IF NOT EXISTS trip (
    trip_id INTEGER PRIMARY KEY AUTOINCREMENT,
    destination VARCHAR(255),
    start_date DATE,
    end_date DATE
);

CREATE TABLE IF NOT EXISTS expense (
    expense_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE,
    amount DOUBLE,
    currency VARCHAR(255),
    category VARCHAR(255),
    payment_method VARCHAR(255)
);